AWSTemplateFormatVersion: "2010-09-09"

Description: >
  IaC for AVP

Parameters:
  CedarJson:
    Type: String
    Description: The Cedar JSON to be used in the PolicyStore resource
  CognitoStackName:
    Type: String
    Description: The name of the Cognito stack

Resources:
  PolicyStore:
    Type: AWS::VerifiedPermissions::PolicyStore
    Properties:
      Description: "Policy store for the documents scenario created via Cloudformation"
      ValidationSettings:
        Mode: STRICT
      Schema:
        CedarJson: !Ref CedarJson

  AllowPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref PolicyStore
      Definition:
        Static:
          Description: "Allow all users to view all documents"
          Statement: |
            permit (
                principal,
                action in [DocumentManagementPlatform::Action::"View"],
                resource
            );

  DenyPolicyTemplate:
    Type: AWS::VerifiedPermissions::PolicyTemplate
    Properties:
      PolicyStoreId: !Ref PolicyStore
      Description: "Template to forbid to a given user to vew any document"
      Statement: |
        forbid (
          principal in ?principal,
          action in [DocumentManagementPlatform::Action::"View"],
          resource in ?resource
        );

  IdentitySource:
    Type: AWS::VerifiedPermissions::IdentitySource
    Properties:
      PolicyStoreId: !Ref PolicyStore
      Configuration:
        CognitoUserPoolConfiguration:
          UserPoolArn:
            Fn::ImportValue: !Sub "${CognitoStackName}-user-pool-arn"
          # ClientIds: !Ref ClientIds
      PrincipalEntityType: DocumentManagementPlatform::User

Outputs:
  PolicyStoreId:
    Description: "Identifier of the Amazon Verified Permissions policy store."
    Value: !Ref PolicyStore
