AWSTemplateFormatVersion: "2010-09-09"

Description: >
  IaC for Cognito

Resources:
  MyCognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: MyUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  MyCognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: MyUserPoolClient
      UserPoolId: !Ref MyCognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

Outputs:
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !Ref MyCognitoUserPool
  UserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !GetAtt MyCognitoUserPoolClient.ClientId
  UserPoolArn:
    Description: The ARN of the Cognito User Pool
    Value: !GetAtt MyCognitoUserPool.Arn
    Export:
      Name: MyUserPoolArn
